baseURL = 'https://babinion.xyz/'
languageCode = 'ro'
title = 'Oleacă profesor'
theme = 'basic'
enableEmoji = false
copyright = "© 2020-2050 <a href='https://github.com/owhyy/website-hugo'>Babin Ion</a>."
description = "Locul unde scriu ce-mi dă mie prin cap"

[taxonomies]
  genres = "genres"
  tag = "tags"

[Permalinks]
  note = "note/:slug"
  book = "book/:slug"

[[params.menu]]
  name = "notițe"
  url = "note/"

[[params.menu]]
  name = "cărți"
  url = "genres/"

[[params.menu]]
  name = "despre"
  url = "about/"
